# Generated by Django 3.0 on 2022-02-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='полное имя')),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('gpa', models.FloatField(verbose_name='Среднее значение GPA')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Account', verbose_name='аккаунт')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('gpa',),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='полное имя')),
                ('topic', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('ruby', 'Ruby'), ('golang', 'GoLang'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('deplhi', 'Deplhi'), ('perl', 'Perl')], default='java', max_length=10, verbose_name='предмет')),
                ('students', models.ManyToManyField(to='djangoapp.Student')),
            ],
            options={
                'verbose_name': 'Профессор',
                'verbose_name_plural': 'Профессоры',
                'ordering': ('topic',),
            },
        ),
    ]
